### PR TITLE
Bug 1759230 - Add the mozilla-vpn-client repo to config4

### PR DESCRIPTION
**Pull request by staktrace**

### CODE REVIEW

**Comment by asutherland** [comment]
Also, thanks for adding this!

**Comment by staktrace** [comment]
The dev run I kicked off failed due to what looks like an intermittent network error on the pine tree:

```
+ parallel --halt now,fail=1
curl: (22) The requested URL returned error: 404
curl: (22) The requested URL returned error: 502
parallel: This job failed:
curl -SsfL --compressed https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.v2.pine.revision.0f60115262f580b0c5d33bcdedf822d999245d16.firefox.win64-searchfox-debug/artifacts/public/build/target.mozsearch-index.zip > win64.mozsearch-index.zip
```

I'm hoping it's intermittent and will just retrigger the dev run.

**Comment by staktrace** [comment]
The repo has submodules which is causing the same error that we ran into at https://bugzilla.mozilla.org/show_bug.cgi?id=958852#c9. I'll update the config to skip submodules.

**Comment by staktrace** [comment]
That worked, merging.

**Pull request merged**
