### PR TITLE
Fix wubkat build

### PR DESCRIPTION
**Pull request by nicolas-guichard**
I managed a successful indexer run on Friday with this (currently deployed on [kdab.searchfox.org](https://kdab.searchfox.org/wubkat/source/)).

### CODE REVIEW

**Comment by dpino** [comment]
Right, the WebKitGTK build broke recently for Ubuntu 24.04 because WebKit Changeset [284276@main](https://commits.webkit.org/284276@main) enabled speech synthesis by default.

Speech synthesis depends on library `libspiel`, which at the present moment is not shipped in Ubuntu 24.04 (neither in any other distro), so the solution to fix the WebKitGTK Ubuntu 24.04 was to adjust the build flags to disable speech synthesis (`-DENABLE_SPEECH_SYNTHESIS=OFF`). I'm less sure about the other flag though (`-DENABLE_GPU_PROCESS=OFF`).

Right now the WebKitGTK Ubuntu 24.04 is building with the following build flags:

```
BUILD_WEBKIT_ARGS="--cmakeargs='-DUSE_LIBBACKTRACE=OFF -DENABLE_SPEECH_SYNTHESIS=OFF'"
```

`-DUSE_LIBBACKTRACE=OFF` is already present in `wubkat/build`.

**Comment by nicolas-guichard** [comment]
> I'm less sure about the other flag though (-DENABLE_GPU_PROCESS=OFF).

That's https://bugs.webkit.org/show_bug.cgi?id=275110 which should eventually be fixed by https://github.com/WebKit/WebKit/pull/30263.
Another options would be to enable `-DDEVELOPER_MODE=ON` which disables the linker script causing the issue [here](https://kdab.searchfox.org/wubkat/source/Source/WebKit/PlatformGTK.cmake#47-50), but that's a much bigger change.

**Comment by dpino** [comment]
OK, thank you for the explanation. I was not aware of the build regression due to https://bugs.webkit.org/show_bug.cgi?id=275110 . The upstream [WebKitGTK for Ubuntu 24.04 bot](https://build.webkit.org/#/builders/68) builds with `DEVELOPER_MODE` on.

**Review by emilio — APPROVED** [review]
Looks good for now, specially given this is tested already. We can remove GPU_PROCESS=OFF and use DEVELOPER_MODE=ON in a separate PR if that's a better configuration (seems it might be, since upstream uses it).

**Comment by asutherland** [comment]
I've manually kicked off a release5 indexer run and re-enabled the "everyday-5am" (defined as 9am UTC) EventBridge rule that kicks off the release5 lambda job.

Just for clarity: the searchfox indexers are still using Ubuntu 22.04; as noted I have a WIP for Ubuntu 24.04 but I got hung up on installing awscli because the most idiomatic way to install it is to use a snap but we don't currently have snaps enabled at all in the image and I'm a bit wary of enabling them.  I suppose curl + run the resulting shell script may be the least bad option there.

**Comment by dpino** [comment]
> I've manually kicked off a release5 indexer run and re-enabled the "everyday-5am" (defined as 9am UTC) EventBridge rule that kicks off the release5 lambda job.
> 
> Just for clarity: the searchfox indexers are still using Ubuntu 22.04; as noted I have a WIP for Ubuntu 24.04 but I got hung up on installing awscli because the most idiomatic way to install it is to use a snap but we don't currently have snaps enabled at all in the image and I'm a bit wary of enabling them. I suppose curl + run the resulting shell script may be the least bad option there.

Thanks for the clarification. Somehow I thought the Mozsearch container was based on Ubuntu 24.04, but double checking the Dockerfile is clear on 22.04 https://github.com/mozsearch/mozsearch/blob/master/infrastructure/Dockerfile#L2.

I agree on staying away from snaps, if possible.  Official WebKitGTK support for Ubuntu 22.04 will end on the April 25th 2025 (one year after the release of Ubuntu 24.04):
  - https://docs.webkit.org/Ports/WebKitGTK%20and%20WPE%20WebKit/DependenciesPolicy.html

However, we're informally extending the life of the distros we support, whenever possible. So very likely, it will be possible to build WebKitGTK in Ubuntu 22.04 after the end of the official support.

Regarding build flags, the upstream [WebKitGTK Ubuntu 22.04](https://build.webkit.org/#/builders/1059) build bot, buils with these CMake flags:

```
BUILD_WEBKIT_ARGS=
    --cmakeargs=-DENABLE_COG=OFF               
    --cmakeargs=-DENABLE_SPEECH_SYNTHESIS=OFF  
    --cmakeargs=-DENABLE_WPE_QT_API=OFF        
    --cmakeargs=-DUSE_JPEGXL=OFF
    --cmakeargs=-DUSE_LIBBACKTRACE=OFF         
    --cmakeargs=-DUSE_SYSTEM_SYSPROF_CAPTURE=NO
    --cmakeargs=-DUSE_WPE_RENDERER=OFF
```

The build flags can be checked at the beginning of the 'compile-webkit' step for every build job, for instance:

  - https://build.webkit.org/#/builders/1059/builds/3508/steps/9/logs/stdio 

Comparing that with the current settings of `wubkat/build` it seems `-DUSE_LCMS=OFF` could be removed.

**Comment by dpino** [comment]
> Looks good for now, specially given this is tested already. We can remove GPU_PROCESS=OFF and use DEVELOPER_MODE=ON in a separate PR if that's a better configuration (seems it might be, since upstream uses it).

The build bots use the script `Tools/Scripts/build-webkit`, which enables DEVELOPER_MODE. The `wubkat/build/` script builds using CMake directly.

**Comment by asutherland** [comment]
The run I kicked off yesterday failed in an intermittent failure mode we've seen several times (excerpt below), but today's run was fine.

The run took 8.5 hours on an m5d.2xlarge which I think means that although [I merged my experimental change so release5 would get an m5d.4xlarge](https://searchfox.org/mozsearch/rev/fd30a84aa37964b65f89121b2f7d34619a45db5b/infrastructure/aws/trigger_common.py#82-85) I either didn't update the lambda jobs or something went wrong when I tried.  Because the lambda job update timestamp is 2024-08-13 for the code bundles, I downloaded the lambda zipball for config5 to sanity check what was going on, but that change wasn't in there.  (Timestamps show the zipball's internal timestamps are for 2024-07-28 corresponding to https://github.com/mozsearch/mozsearch/pull/805#issuecomment-2254799179 so it's not clear if the uploads failed to take like they're over the size limit again, or if the old zip files were still around.  There is a [mv that should probably be a mv -f](https://searchfox.org/mozsearch/rev/fd30a84aa37964b65f89121b2f7d34619a45db5b/infrastructure/aws/build-lambda-indexer-start.sh#63) that could explain that happening so I'm going to fix that and re-generate the lambdas and try and close out the Ubuntu 24.04 migration tonight just to avoid having any confusion or lingering WIPs that complicate things.

The intermittent failure for posterity is:
```
[ 98%] Generating documentation: WebKit
MOZSEARCH: /mnt/index-scratch/wubkat/git /mnt/index-scratch/wubkat/analysis/ /mnt/index-scratch/wubkat/objdir/
[ 98%] Building C object Tools/MiniBrowser/gtk/CMakeFiles/MiniBrowser.dir/BrowserSearchBox.c.o
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gidocgen/gidocmain.py", line 74, in run
    res = options.run_func(options)
  File "/usr/lib/python3/dist-packages/gidocgen/gdgendeps.py", line 86, in run
    parser.parse(options.infile)
  File "/usr/lib/python3/dist-packages/gidocgen/gir/parser.py", line 91, in parse
    tree = ET.parse(girfile)
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1222, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 580, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
make[2]: *** [Source/WebKit/CMakeFiles/doc-WebKit.dir/build.make:76: Documentation/webkitgtk-6.0/index.html] Error 1
make[1]: *** [CMakeFiles/Makefile2:2009: Source/WebKit/CMakeFiles/doc-WebKit.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by aperezdc** [comment]
> The run I kicked off yesterday failed in an intermittent failure mode we've seen several times (excerpt below), but today's run was fine.
> 
> The run took 8.5 hours on an m5d.2xlarge which I think means that although [I merged my experimental change so release5 would get an m5d.4xlarge](https://searchfox.org/mozsearch/rev/fd30a84aa37964b65f89121b2f7d34619a45db5b/infrastructure/aws/trigger_common.py#82-85) I either didn't update the lambda jobs or something went wrong when I tried. Because the lambda job update timestamp is 2024-08-13 for the code bundles, I downloaded the lambda zipball for config5 to sanity check what was going on, but that change wasn't in there.
> 
> Timestamps show the zipball's internal timestamps are for 2024-07-28 corresponding to [mozsearch/mozsearch#805 (comment)](https://github.com/mozsearch/mozsearch/pull/805#issuecomment-2254799179) so it's not clear if the uploads failed to take like they're over the size limit again, or if the old zip files were still around. There is a [mv that should probably be a mv -f](https://searchfox.org/mozsearch/rev/fd30a84aa37964b65f89121b2f7d34619a45db5b/infrastructure/aws/build-lambda-indexer-start.sh#63) that could explain that happening so I'm going to fix that and re-generate the lambdas and try and close out the Ubuntu 24.04 migration tonight just to avoid having any confusion or lingering WIPs that complicate things.
> 
> The intermittent failure for posterity is:
> 
> ```
> [ 98%] Generating documentation: WebKit
> MOZSEARCH: /mnt/index-scratch/wubkat/git /mnt/index-scratch/wubkat/analysis/ /mnt/index-scratch/wubkat/objdir/
> [ 98%] Building C object Tools/MiniBrowser/gtk/CMakeFiles/MiniBrowser.dir/BrowserSearchBox.c.o
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/gidocgen/gidocmain.py", line 74, in run
>     res = options.run_func(options)
>   File "/usr/lib/python3/dist-packages/gidocgen/gdgendeps.py", line 86, in run
>     parser.parse(options.infile)
>   File "/usr/lib/python3/dist-packages/gidocgen/gir/parser.py", line 91, in parse
>     tree = ET.parse(girfile)
>   File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1222, in parse
>     tree.parse(source, parser)
>   File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 580, in parse
>     self._root = parser._parse_whole(source)
> xml.etree.ElementTree.ParseError: no element found: line 1, column 0
> make[2]: *** [Source/WebKit/CMakeFiles/doc-WebKit.dir/build.make:76: Documentation/webkitgtk-6.0/index.html] Error 1
> make[1]: *** [CMakeFiles/Makefile2:2009: Source/WebKit/CMakeFiles/doc-WebKit.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> ```

I think you may want to add `-DENABLE_DOCUMENTATION=OFF -DENABLE_INTROSPECTION=OFF` to avoid running `gi-docgen`: the source code indexing doesn't benefit from having the API reference documentation built, the intermittent failure won't be hit, and the build time will be a tad shorter 😉

**Comment by asutherland** [comment]
> I think you may want to add `-DENABLE_DOCUMENTATION=OFF -DENABLE_INTROSPECTION=OFF` to avoid running `gi-docgen`: the source code indexing doesn't benefit from having the API reference documentation built, the intermittent failure won't be hit, and the build time will be a tad shorter 😉

Thanks, I'll do that!

**Comment by asutherland** [comment]
After https://github.com/mozsearch/mozsearch-mozilla/pull/264 we're getting mysterious failures when building skia where the make output is not informative.  Even if I log in and do `export VERBOSE=1` to get more insight into what's going on, it's still not particularly useful.

Here's what the indexer emailed this morning:
```
[ 28%] Building CXX object Source/ThirdParty/skia/CMakeFiles/Skia.dir/modules/skcms/src/skcms_TransformSkx.cc.o
MOZSEARCH: /mnt/index-scratch/wubkat/git /mnt/index-scratch/wubkat/analysis/ /mnt/index-scratch/wubkat/objdir/
MOZSEARCH: /mnt/index-scratch/wubkat/git /mnt/index-scratch/wubkat/analysis/ /mnt/index-scratch/wubkat/objdir/
MOZSEARCH: /mnt/index-scratch/wubkat/git /mnt/index-scratch/wubkat/analysis/ /mnt/index-scratch/wubkat/objdir/
MOZSEARCH: /mnt/index-scratch/wubkat/git /mnt/index-scratch/wubkat/analysis/ /mnt/index-scratch/wubkat/objdir/
MOZSEARCH: /mnt/index-scratch/wubkat/git /mnt/index-scratch/wubkat/analysis/ /mnt/index-scratch/wubkat/objdir/
MOZSEARCH: /mnt/index-scratch/wubkat/git /mnt/index-scratch/wubkat/analysis/ /mnt/index-scratch/wubkat/objdir/
MOZSEARCH: /mnt/index-scratch/wubkat/git /mnt/index-scratch/wubkat/analysis/ /mnt/index-scratch/wubkat/objdir/
MOZSEARCH: /mnt/index-scratch/wubkat/git /mnt/index-scratch/wubkat/analysis/ /mnt/index-scratch/wubkat/objdir/
MOZSEARCH: /mnt/index-scratch/wubkat/git /mnt/index-scratch/wubkat/analysis/ /mnt/index-scratch/wubkat/objdir/
MOZSEARCH: /mnt/index-scratch/wubkat/git /mnt/index-scratch/wubkat/analysis/ /mnt/index-scratch/wubkat/objdir/
MOZSEARCH: /mnt/index-scratch/wubkat/git /mnt/index-scratch/wubkat/analysis/ /mnt/index-scratch/wubkat/objdir/
MOZSEARCH: /mnt/index-scratch/wubkat/git /mnt/index-scratch/wubkat/analysis/ /mnt/index-scratch/wubkat/objdir/
MOZSEARCH: /mnt/index-scratch/wubkat/git /mnt/index-scratch/wubkat/analysis/ /mnt/index-scratch/wubkat/objdir/
MOZSEARCH: /mnt/index-scratch/wubkat/git /mnt/index-scratch/wubkat/analysis/ /mnt/index-scratch/wubkat/objdir/
MOZSEARCH: /mnt/index-scratch/wubkat/git /mnt/index-scratch/wubkat/analysis/ /mnt/index-scratch/wubkat/objdir/
MOZSEARCH: /mnt/index-scratch/wubkat/git /mnt/index-scratch/wubkat/analysis/ /mnt/index-scratch/wubkat/objdir/
[ 28%] Linking CXX static library ../../../lib/libSkia.a
[ 28%] Built target Skia
make: *** [Makefile:166: all] Error 2
+ handle_tree_error 'tree build script'
```

I did try adding `-DUSE_SKIA=OFF` after glancing at https://bugs.webkit.org/show_bug.cgi?id=280605 but it didn't seem like that actually did anything; the config said:
```
-- Enabled features:                                                                                                                                                                                                  
--  ENABLE_BUBBLEWRAP_SANDBOX ..................... OFF                                                                                                                                                               
--  ENABLE_DOCUMENTATION                            OFF                                                                                                                                                               
--  ENABLE_DRAG_SUPPORT ........................... ON                                                                                                                                                                
--  ENABLE_GAMEPAD                                  ON                                                                                                                                                                
--  ENABLE_INTROSPECTION .......................... OFF                                                                                                                                                               
--  ENABLE_JOURNALD_LOG                             ON                                                                                                                                                                
--  ENABLE_MINIBROWSER ............................ ON                                                                                                                                                                
--  ENABLE_PDFJS                                    ON                                                                                                                                                                
--  ENABLE_QUARTZ_TARGET .......................... OFF                                                                                                                                                               
--  ENABLE_SPEECH_SYNTHESIS                         OFF                                                                                                                                                               
--  ENABLE_SPELLCHECK ............................. ON                                                                                                                                                                
--  ENABLE_TOUCH_EVENTS                             ON                                                                                                                                                                
--  ENABLE_VIDEO .................................. ON                                                                                                                                                                
--  ENABLE_WAYLAND_TARGET                           ON                                                                                                                                                                
--  ENABLE_WEBDRIVER .............................. ON                                                                                                                                                                
--  ENABLE_WEB_AUDIO                                ON                                                                                                                                                                
--  ENABLE_X11_TARGET ............................. ON                                                                                                                                                                
--  USE_AVIF                                        ON                                                                                                                                                                
--  USE_GBM ....................................... ON                                                                                                                                                                
--  USE_GSTREAMER_TRANSCODER                        ON                                                                                                                                                                
--  USE_GSTREAMER_WEBRTC .......................... OFF                                                                                                                                                               
--  USE_GTK4                                        ON                                                                                                                                                                
--  USE_JPEGXL .................................... OFF                                                                                                                                                               
--  USE_LCMS                                        OFF                                                                                                                                                               
--  USE_LIBBACKTRACE .............................. OFF                                                                                                                                                               
--  USE_LIBDRM                                      ON                                                                                                                                                                
--  USE_LIBHYPHEN ................................. ON                                                                                                                                                                
--  USE_LIBSECRET                                   ON                                                                                                                                                                
--  USE_SOUP2 ..................................... OFF                                                                                                                                                               
--  USE_SYSTEM_SYSPROF_CAPTURE                      OFF                                                                                                                                                               
--  USE_WOFF2 ..................................... ON                                                                                                                                                                
-- Configuring done (3.5s)                                                                                                                                                                                            
-- Generating done (2.7s)            
```

**Comment by asutherland** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1923545 to track breakage and landed a reversion of the developer-mode enabling commit.  We'll see what happens tomorrow.

**Pull request merged**
