### PR TITLE
Bug 1883953 - Add android-aarch64.

### PR DESCRIPTION
**Pull request by nicolas-guichard**
This is currently up on kdab.searchfox.org using [this Try run](https://treeherder.mozilla.org/jobs?repo=try&revision=36722e667ecbdf459e69861ad735edb9f0677e65). This requires changes to m-c which I have not submitted for review yet, thus marking this as WIP.

### CODE REVIEW

**Review by asutherland — CHANGES_REQUESTED** [review]
Thanks!  A logistical complication is that the change in https://phabricator.services.mozilla.com/D217402 will only update mozilla-central, but this logic is used on beta, release, esr128, and esr115 too.  While to some extent we can perform uplifts of that PR to the other branches, it might be most pragmatic for us to:
- Leave android-armv7 around
- Do add android-aarch64
- Add both android platforms to the logic that prevents us from complaining about missing ios and macosx64-aarch64 jobs.

This will avoid us receiving email warnings for the older branches or ignoring their armv7 builds.

**Comment by nicolas-guichard** [comment]
Ah yes indeed. That should cover both cases then.

**Comment by arai-a** [comment]
can the commit message be reworded to avoid confusion?

**Comment by nicolas-guichard** [comment]
Sure, thanks for reminding me.

**Review by asutherland — APPROVED** [review]
Thanks!

**Pull request merged**
