### PR TITLE
Bug 1584119 - Add ccov_root to mozilla-central configuration

### PR DESCRIPTION
**Pull request by marco-c**

### CODE REVIEW

**Comment by staktrace** [comment]
Is this associated with a bug? If so please put a bug number in the commit message. LGTM otherwise.

**Comment by marco-c** [comment]
No, it isn't. I can open a bug first if you prefer.

**Comment by marco-c** [comment]
Or we could link it to https://bugzilla.mozilla.org/show_bug.cgi?id=1584119.

**Comment by staktrace** [comment]
Yeah linking it to the existing bug is fine. Just so there's some way to get more context during code archaeology :)

**Comment by marco-c** [comment]
> Yeah linking it to the existing bug is fine. Just so there's some way to get more context during code archaeology :)

Done!

**Comment by staktrace** [comment]
Thanks!

**Pull request merged**
