### PR TITLE
[WebKitGTK] Disable USE_LIBBACKTRACE

### PR DESCRIPTION
**Pull request by dpino**
Flag `USE_LIBBACKTRACE` was enabled by default in https://github.com/WebKit/WebKit/pull/18807. This caused an interruption of the WebKitGTK Ubuntu LTS bot. The flag has to be disabled (See https://bugs.webkit.org/show_bug.cgi?id=262837).

### CODE REVIEW

**Comment by dpino** [comment]
cc @emilio @asutherland

**Comment by asutherland** [comment]
Thanks!

**Comment by asutherland** [comment]
I see from https://build.webkit.org/#/builders/68 that https://build.webkit.org/#/builders/68/builds/28049 just completed with a fresh revision of `29c5ff369592c83ac7da4d10cef8693b713de8d8` whereas config5 just finished with a revision of `9709f5c78a15a0ae1e723096557a6a060822d868` corresponding to the previous successful build of https://build.webkit.org/#/builders/68/builds/28026 before things caught fire.  So I'm going to retrigger config5 so we can confirm this fix makes things happy, etc.

**Comment by asutherland** [comment]
I retriggered again because that triggered run decided the last successful revision was "null" but when I just ran the script again locally I'm getting `e21786e1635702a6ca7c1e30290f32e8a97fec23`

**Comment by dpino** [comment]
The [GTK-Linux-64-bit-Release-Ubuntu-LTS-Build](https://build.webkit.org/#/builders/68) bot is green now and the last successful build is e21786e1635702a6ca7c1e30290f32e8a97fec23 ([269058@main](https://build.webkit.org/#/builders/68/builds/28051))

**Comment by asutherland** [comment]
Yes, that was the one the most recent re-trigger picked, and we now have that indexed revision up at https://searchfox.org/wubkat/commit/e21786e1635702a6ca7c1e30290f32e8a97fec23 (this just finished recently), so things should be happy again moving forward.

**Pull request merged**
